#! /bin/sh

# Reload sxhkd
pkill sxhkd
sxhkd &

# Add steroids and cocaine to my keyboard
xset r rate 300 50

# Reload polybar
pkill polybar
polybar -c ~/.config/polybar/config top &

# Reload xsettingsd
pkill xsettingsd
xsettingsd &

# set the wallpaper
feh --bg-fill ~/.wallpaper.jpg

# Reload compton
pkill compton
compton -b &

# Set cursor theme
xsetroot -cursor_name left_ptr

# Let the important things running with some priority
sudo renice -n -10 $(pgrep bspwm)
sudo renice -n -10 $(pgrep sxhkd)
sudo renice -n -10 $(pgrep compton)
sudo renice -n -10 $(pgrep polybar)
sudo renice -n -10 $(pgrep emacs)

###################
## configuration ##
###################

## workspace name
bspc monitor -d '' '' '' '' '' ''  '' '' ''
#bspc monitor -d '' '' '' '' '' '' '' '' '' ''
#bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

## common bspwm configuration
bspc config border_width        0
bspc config window_gap         	14
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config top_padding 44
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0


## color settings
bspc config focused_border_color "#8f8f8f"
bspc config normal_border_color "#2f343f"
bspc config border_width 0

# Rules

# Floaters
bspc rule -a URxvt:float state=floating follow=on
bspc rule -a Termite:float state=floating follow=on
bspc rule -a feh state=pseudo_tiled follow=on

# Configure the music desktop
#bspc rule -a Vlc desktop='^8' follow=on focus=on
MUSIC_DESKTOP=$(bspc query -D | tr '\n' ' ' | cut -d ' ' -f 8)

bspc config -d $MUSIC_DESKTOP window_gap 80
bspc config -d $MUSIC_DESKTOP top_padding 60
bspc config -d $MUSIC_DESKTOP bottom_padding 40
bspc config -d $MUSIC_DESKTOP left_padding 8 0
bspc config -d $MUSIC_DESKTOP right_padding 0

# Start the stream daemon
mkdir -p /var/run/snapclient/
chown ${USER}:${USER} /var/run/snapclient
${HOME}/.bin/snapclient -h localhost -p 1704 --user ${USER} -d

# If emacs isn't started, start it in server mode
if ! pgrep 'emacs' > /dev/null
then
    emacs --daemon
fi
